version: "3"
services:
  kafka:
    image: 'bitnami/kafka:3.4.0'
    container_name: kafka1
    ports:
    - '9092:9092'
    - '29092:29092'
    extra_hosts:
    - "kafka1:127.0.0.1"
    - "kafka2:${IP_KAFKA2}"
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_LISTENERS=SSL://0.0.0.0:9092,EXTERNAL://kafka:29092
    - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://kafka1:9092,EXTERNAL://${IP_KAFKA1}:29092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SSL:SSL,EXTERNAL:SASL_SSL
    - KAFKA_CFG_ZOOKEEPER_CONNECT=${IP_KAFKA2}:2181
    - KAFKA_ZOOKEEPER_PROTOCOL= SASL
    - KAFKA_ZOOKEEPER_USER=admin
    - KAFKA_ZOOKEEPER_PASSWORD=adminpassword
    - KAFKA_CLIENT_USERS=kafka
    - KAFKA_CLIENT_PASSWORDS=kafkapassword
    - KAFKA_CERTIFICATE_PASSWORD=123456 
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SSL
    - KAFKA_TLS_TYPE=JKS
    - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf
    - KAFKA_ENABLE_KRAFT=no
    volumes:
    - kafka_data:/bitnami/kafka
    - '../config/kafka/kafka.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
    - '../config/kafka/kafka.server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
    - '../config/kafka/kafka_server_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf:ro'
    - '../config/kafka/kafka.client.properties:/opt/bitnami/kafka/config/kafka_client_jaas.conf:ro'
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    network_mode: host
    extra_hosts:
    - "mongodb:${IP_KAFKA1}"
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - mongo_data:/data/db
    - ../config/mongoDB/rs-init.sh:/rs-init.sh
    - ../config/mongoDB/init.js:/init.js
    command: /usr/bin/mongod --replSet rs0 --bind_ip 127.0.0.1,mongodb
    depends_on:
    - kafka
  python:
    build: .
    container_name: python-kafka
    depends_on:
    - mongodb
volumes:
  kafka_data:
  mongo_data:
