version: "3"
services:
  docker-registry:
    image: 'registry:2.7'
    container_name: docker-registry
    restart: always
    extra_hosts:
    - "masterkub:${IP_KAFKA}"
    ports:
    - '${IP_KAFKA}:5000:5000'
    volumes:
    - registry-data:/var/lib/registry
volumes:
  registry-data: